name: ilaydaumit
description: İlayda ve Ümit için özel uygulama
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  agora_rtc_engine: ^6.3.0
  image_picker: ^1.0.5
  table_calendar: ^3.0.9
  intl: ^0.18.1

flutter:
  uses-material-design: true
  
  # Uygulama ikonu ve splash screen için
  assets:
    - assets/images/